name: Unit Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore Faaast.sln
      
    - name: Build
      run: dotnet build --no-restore Faaast.sln

    - name: Test with the dotnet CLI
      run: dotnet test --no-build src/Faaast.Tests/Faaast.Tests.csproj /p:CollectCoverage=true /p:CoverletOutput=TestResults /p:CoverletOutputFormat=lcov
      env:
        ASPNETCORE_ENVIRONMENT: Development
        
    - name: Publish coverage
      if: always()
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: /home/runner/work/Faaast/Faaast/src/Faaast.Tests/TestResults.info
